import Head from 'next/head'
import { GetStaticProps } from 'next';
import { gql } from "@apollo/client";
import client from "../../apollo-client";

import Banner from '../components/BannerHome'
import { DisplayCourses } from '../components/DisplayCourses'

import { CoursesType } from '../types/courses.type';
import Header from '../components/Header';

interface HomeProps {
  courses: CoursesType[]
}

export default function Home({ courses }: HomeProps) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Banner />
        <DisplayCourses
          courses={courses}
        />
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const { data } = await client.query({
    query: gql`
      query Courses {
        courses {
          id
          publishedAt
          slug
          title
          teachers {
            id
            name
            picture {
              url
            }
          }
          assets {
            id
            url
          }
          updatedAt
          createdAt
        }
      }
    `,
  });

  const courses = data.courses;

  return {
    props: {
      courses
    },
  } 
}
