import Head from 'next/head'
import { GetStaticProps } from 'next';
import { gql } from "@apollo/client";
import client from "../../apollo-client";

import Banner from '../components/BannerHome'
import { DisplayCourses } from '../components/DisplayCourses'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner />
        <DisplayCourses />
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const { data } = await client.query({
    query: gql`
      query Courses {
        courses {
          createdAt
          id
          publishedAt
          slug
          title
          updatedAt
        }
      }
    `,
  });

  console.log(data)

  return {
    props: {
      data
    },
  } 
}
